begin;
insert into public.membros (nome) values ('Adelaide Vitória Gomes de Souza');
insert into public.membros (nome) values ('Agnoilson de Oliveira  Pires');
insert into public.membros (nome) values ('Ailton Soares Xavier');
insert into public.membros (nome) values ('Alice Mara Messias Borges da Silva');
insert into public.membros (nome) values ('Amanda Paula Ribeiro');
insert into public.membros (nome) values ('Ana Lucia Marcolino de Almeida');
insert into public.membros (nome) values ('Andressa Alves de Araujo');
insert into public.membros (nome) values ('Angélica de Góis Mendes');
insert into public.membros (nome) values ('Beatriz dos Santos Silva');
insert into public.membros (nome) values ('Boaz Goes Rosa');
insert into public.membros (nome) values ('Brenda Pitinga Nogueira');
insert into public.membros (nome) values ('Bruno Aparecido da Silva Cruz');
insert into public.membros (nome) values ('Camila Sacal dos Santos Luiz');
insert into public.membros (nome) values ('Carla Magela da Silva Costa');
insert into public.membros (nome) values ('Carlos Alberto Da Silva');
insert into public.membros (nome) values ('Carlos Sergio Santana Pinto');
insert into public.membros (nome) values ('Cecília dos Santos Lourenço');
insert into public.membros (nome) values ('Cinthia Simone Roque Silva');
insert into public.membros (nome) values ('Cristiane Alves da Silva');
insert into public.membros (nome) values ('Daniela Dos Santos Luiz');
insert into public.membros (nome) values ('Danielle Dos Santos Silva Farias');
insert into public.membros (nome) values ('Débora da Silva Araujo');
insert into public.membros (nome) values ('Dinalva Rosa Rodrigues Papa');
insert into public.membros (nome) values ('Diorcília Almeida Matos');
insert into public.membros (nome) values ('Domingos Alves Costa');
insert into public.membros (nome) values ('Edilene Gomes dos Santos Pereira');
insert into public.membros (nome) values ('Edinaide Leite da Silva');
insert into public.membros (nome) values ('Edinalva Maria da Silva Candido');
insert into public.membros (nome) values ('Edson Magela Cardoso Costa');
insert into public.membros (nome) values ('Eliane Alves Das Graças de Oliveira');
insert into public.membros (nome) values ('Elias Queiroz de Melo');
insert into public.membros (nome) values ('Eliene Luana Alves de Oliveira');
insert into public.membros (nome) values ('Eliseu Angelo Pereira');
insert into public.membros (nome) values ('Emiliane Alves das Graças Cunha');
insert into public.membros (nome) values ('Ester Sonia Alvez da Rocha Araujo');
insert into public.membros (nome) values ('Expedito Caetano');
insert into public.membros (nome) values ('Fábio André dos Anjo Rosa');
insert into public.membros (nome) values ('Fernanda Costa de Souza');
insert into public.membros (nome) values ('Fernanda dos Santos Alves');
insert into public.membros (nome) values ('Francineide Maria Laurentino da Silva');
insert into public.membros (nome) values ('Francisco Ferreira Machado');
insert into public.membros (nome) values ('Francisco Marques de Araujo Neto');
insert into public.membros (nome) values ('Frankefre da Silva Laurentino');
insert into public.membros (nome) values ('Gabriel Rodrigues de Oliveira');
insert into public.membros (nome) values ('Gean Marcullis');
insert into public.membros (nome) values ('Geraldo Magela da Silva');
insert into public.membros (nome) values ('Gerlane Rafaelly de Melo Reis Anjo');
insert into public.membros (nome) values ('Gisele das Dores Ferreira Santos');
insert into public.membros (nome) values ('Guaraci Aparecido de Camargo');
insert into public.membros (nome) values ('Guiomar Batista Reis Pereira');
insert into public.membros (nome) values ('Ilma Alves das Graças');
insert into public.membros (nome) values ('Iraildes de jesus Silva rabelo');
insert into public.membros (nome) values ('Itamar Soares Neves');
insert into public.membros (nome) values ('Ivonia Das Graças Santos');
insert into public.membros (nome) values ('System.Xml.XmlElement');
insert into public.membros (nome) values ('Jafia Lany Silva Laurentino');
insert into public.membros (nome) values ('Jamily Rayza');
insert into public.membros (nome) values ('System.Xml.XmlElement');
insert into public.membros (nome) values ('Jardielle Rafaela');
insert into public.membros (nome) values ('João Paulo Vieira');
insert into public.membros (nome) values ('System.Xml.XmlElement');
insert into public.membros (nome) values ('Joice Caroline Messias');
insert into public.membros (nome) values ('Josafá Soares da Silva');
insert into public.membros (nome) values ('José Antônio das Graças');
insert into public.membros (nome) values ('José Antônio De Oliveira Filho');
insert into public.membros (nome) values ('System.Xml.XmlElement');
insert into public.membros (nome) values ('José Leonardo De Moura Bueno Lopes');
insert into public.membros (nome) values ('José Luan');
insert into public.membros (nome) values ('Juliana Magela da Silva');
insert into public.membros (nome) values ('Jussara Silva de Morais');
insert into public.membros (nome) values ('Katiane Soares da Silva Lira');
insert into public.membros (nome) values ('Laina Anne Barbosa Cunha M. de Castro');
insert into public.membros (nome) values ('Lana Júlia Roque Silva');
insert into public.membros (nome) values ('Larissa Expedita Lopes Firmino');
insert into public.membros (nome) values ('Lilliane Patrícia');
insert into public.membros (nome) values ('Lorena Ribeiro Silva');
insert into public.membros (nome) values ('Lucas De Jesus Barbosa');
insert into public.membros (nome) values ('Luciana  Gonçalves De Souza Pereira');
insert into public.membros (nome) values ('Lucimary Silva de Castro');
insert into public.membros (nome) values ('Manoel Abidias Batista dos Santos');
insert into public.membros (nome) values ('Marcia das Dores Magalhães Rodrigues');
insert into public.membros (nome) values ('Marciana Aparecida Rezende de Oliveira');
insert into public.membros (nome) values ('Marco Antonio Mendes');
insert into public.membros (nome) values ('Marcos Paulo Silva Rabelo');
insert into public.membros (nome) values ('Maria Aparecida Prudente Camargo');
insert into public.membros (nome) values ('Maria do Carmo Gomes');
insert into public.membros (nome) values ('Maria Isabel dos Santos');
insert into public.membros (nome) values ('Maria José  Ramos Caetano');
insert into public.membros (nome) values ('Maria José Gomes do Nascimento');
insert into public.membros (nome) values ('Marluce Rosa de Jesus Neves');
insert into public.membros (nome) values ('Mateus Messias da Silva');
insert into public.membros (nome) values ('Miralva Espírito Santo de Oliveira');
insert into public.membros (nome) values ('Nathan Sacal dos Santos Luiz');
insert into public.membros (nome) values ('Neire Sales Rodrigues Pinto');
insert into public.membros (nome) values ('Osvaldo José Pereira');
insert into public.membros (nome) values ('Pablo Henrique de Jesus Barbosa Jesus Barbosa');
insert into public.membros (nome) values ('Pedrina Ferreira Machado');
insert into public.membros (nome) values ('Raevin Kalil Oliveira Mesquita');
insert into public.membros (nome) values ('Raissa Lorena Felix Laurentino');
insert into public.membros (nome) values ('Raquel Alves de Araujo');
insert into public.membros (nome) values ('Renan Fernandes dos Santos');
insert into public.membros (nome) values ('Rennab Kellys de Oliveira');
insert into public.membros (nome) values ('System.Xml.XmlElement');
insert into public.membros (nome) values ('Robert Fernandes dos Santos');
insert into public.membros (nome) values ('Rose Elaine Machado da Silva');
insert into public.membros (nome) values ('Rosimar Pitinga Nogueira');
insert into public.membros (nome) values ('Rosino dos Santos Luiz');
insert into public.membros (nome) values ('Rubens Alves de Castro');
insert into public.membros (nome) values ('Ruth Ferreira da Rosa Araujo');
insert into public.membros (nome) values ('Sandro Da Silva Bezerra');
insert into public.membros (nome) values ('Sara Cristina Goes Rosa');
insert into public.membros (nome) values ('Sara Regina Pereira');
insert into public.membros (nome) values ('Sebastião Luís da Cunha');
insert into public.membros (nome) values ('Silas Aquila De Souza Silva');
insert into public.membros (nome) values ('Simone Aparecida Roque Silva');
insert into public.membros (nome) values ('Sulamita Hadassa Felix Laurentino');
insert into public.membros (nome) values ('Taiemy Luana De Oliveira');
insert into public.membros (nome) values ('Taizes Alves');
insert into public.membros (nome) values ('Tiago Benedito da Silva Silva');
insert into public.membros (nome) values ('Valmira Auxiliadora Feleciana Dias Luiz');
insert into public.membros (nome) values ('Valneir Gomes Cordeiro Nobre');
insert into public.membros (nome) values ('Valter Leite da Silva');
insert into public.membros (nome) values ('Vinicius Pereira da Silva Fernandes');
insert into public.membros (nome) values ('Vytor Gabriel Messias Xavier');
insert into public.membros (nome) values ('Wanderson Alves das Graças');
insert into public.membros (nome) values ('Weder Luan De Oliveira');
insert into public.membros (nome) values ('Welton de Oliveira Santos');
insert into public.membros (nome) values ('Wemerson Alves das Graças');
insert into public.membros (nome) values ('Weverson Luan Alves de Oliveira');
insert into public.membros (nome) values ('Zenaide Rodrigues Pereira');
commit;
